# Makefile

CC = gcc
CPPFLAGS =
CFLAGS = -Wall -Wextra
LDFLAGS = -pthread
LDLIBS =

EXE = hello hello_id hello_parity

all: ${EXE}

hello:
hello_id:
hello_parity:

.PHONY: clean

clean:
	${RM} ${EXE}

# END
